name: secure_vault_id
description: Password manager app with biometric authentication
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15
  local_auth: ^2.1.0
  encrypt: ^5.0.1
  path_provider: ^2.0.11
  intl: ^0.18.0
  pinput: ^3.0.0
  file_picker: ^8.1.4
  fl_chart: ^0.65.0
  share_plus: ^7.2.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

platforms:
  android: null
  ios: null
